-- H2-COMPATIBLE SCHEMA;
CREATE TABLE IF NOT EXISTS SNAPSHOTS
(
    ENTITY_ID       VARCHAR(255)  NOT NULL,
    SEQUENCE_NUMBER BIGINT        NOT NULL CHECK (SEQUENCE_NUMBER > 0),
    STATE_DATA      TEXT          NOT NULL,
    TIMESTAMP       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ENTITY_ID, SEQUENCE_NUMBER)
    );

CREATE TABLE IF NOT EXISTS EVENT_JOURNAL
(
    ENTITY_ID           VARCHAR(255)  NOT NULL,
    SEQUENCE_NUMBER     BIGINT        NOT NULL CHECK (SEQUENCE_NUMBER > 0),
    EVENT_DATA          TEXT          NOT NULL,
    TIMESTAMP           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PARTITION_RESIDENCE INTEGER       NOT NULL DEFAULT 0,
    PRIMARY KEY (ENTITY_ID, SEQUENCE_NUMBER)
    );

CREATE TABLE IF NOT EXISTS EVENT_OUTBOX
(
    ENTITY_ID           VARCHAR(255)  NOT NULL,
    SEQUENCE_NUMBER     BIGINT        NOT NULL CHECK (SEQUENCE_NUMBER > 0),
    EVENT_DATA          TEXT          NOT NULL,
    TIMESTAMP           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROCESSED           BOOLEAN       NOT NULL DEFAULT FALSE,
    EVENT_ID            VARCHAR(255)  NOT NULL,
    PARTITION_RESIDENCE INTEGER       NOT NULL DEFAULT 0,
    PRIMARY KEY (ENTITY_ID, SEQUENCE_NUMBER)
    );