CREATE TABLE SNAPSHOTS
(
    ENTITY_ID       varchar(255) NOT NULL,
    SEQUENCE_NUMBER BIGINT       NOT NULL CHECK (SEQUENCE_NUMBER > 0),
    STATE_DATA      TEXT         NOT NULL,
    TIMESTAMP       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ENTITY_ID, SEQUENCE_NUMBER)
);

CREATE TABLE EVENT_JOURNAL
(
    ENTITY_ID       VARCHAR(255) NOT NULL,
    SEQUENCE_NUMBER BIGINT       NOT NULL CHECK (SEQUENCE_NUMBER > 0),
    EVENT_DATA      TEXT         NOT NULL,
    TIMESTAMP       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SHARD           INTEGER      NOT NULL DEFAULT 0,
    PRIMARY KEY (ENTITY_ID, SEQUENCE_NUMBER)
);

CREATE TABLE EVENT_OUTBOX
(
    EVENT_ID   VARCHAR(255) NOT NULL,
    EVENT_DATA TEXT         NOT NULL,
    CLAIM_ID   VARCHAR(36) NULL,
    CLAIMED_AT TIMESTAMP NULL,
    PRIMARY KEY (EVENT_ID)
);