CREATE TABLE TEST_SNAPSHOTS
(
    ENTITY_ID       varchar(255) NOT NULL,
    SEQUENCE_NUMBER BIGINT       NOT NULL CHECK (SEQUENCE_NUMBER > 0),
    STATE_DATA      BLOB         NOT NULL,
    TIMESTAMP       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ENTITY_ID, SEQUENCE_NUMBER)
);

CREATE TABLE TEST_EVENT_JOURNAL
(
    ENTITY_ID         VARCHAR(255) NOT NULL,
    SEQUENCE_NUMBER   BIGINT       NOT NULL CHECK (SEQUENCE_NUMBER > 0),
    EVENT_DATA        BLOB         NOT NULL,
    TIMESTAMP         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ORIGIN_COMMAND_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (ENTITY_ID, SEQUENCE_NUMBER)
);

CREATE TABLE TEST_EVENT_OUTBOX
(
    EVENT_ID   VARCHAR(255) NOT NULL,
    EVENT_DATA BLOB         NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CLAIM_ID   VARCHAR(255) NULL,
    CLAIMED_AT TIMESTAMP NULL,
    PRIMARY KEY (EVENT_ID)
);

CREATE INDEX TEST_EVENT_OUTBOX_CREATED_AT ON TEST_EVENT_OUTBOX (CREATED_AT ASC);
CREATE INDEX TEST_EVENT_OUTBOX_CLAIM_ID ON TEST_EVENT_OUTBOX (CLAIM_ID ASC);